on: [push,pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    #  Login to Azure
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Maven Build and package
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml

   # deploy web app using publish profile credentials
    - uses: azure/webapps-deploy@v1
      with: 
        app-name: deardiary  # Replace with your app name
        package: '${{ github.workspace }}/target/*.jar'
    
    #Logout of Azure
    - name: Azure logout
      run: |
        az logout
